### Normal itamae task
require 'itamae-mitsurin/mitsurin/itamae_task'

### Normal Serverspec task
require 'itamae-mitsurin/mitsurin/serverspec_task'

### Change the nodes to be read by a target mode
### `rake -T <target>` to load a 'nodes/<target>'
# require 'itamae-mitsurin/mitsurin/itamae_with_target_task'
# require 'itamae-mitsurin/mitsurin/serverspec_with_target_task'

### Itamae local mode
# require 'itamae-mitsurin/mitsurin/local_task'
